# Generated by Django 5.1.7 on 2025-03-27 00:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.TextField(blank=True, max_length=200, null=True)),
                ('actors', models.TextField(blank=True, max_length=200, null=True)),
                ('sinopse', models.TextField(max_length=200)),
                ('poster_url', models.CharField(max_length=200)),
                ('rated', models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, null=True)),
                ('launch_date', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.IntegerField()),
                ('stars', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('review', models.TextField(max_length=250)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)])),
                ('show', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestao.movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review - Movie',
                'verbose_name_plural': 'Reviews - Movies',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='user_reviews',
            field=models.ManyToManyField(through='gestao.ReviewMovies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('review', models.TextField(max_length=250)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)])),
                ('show', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review - Series',
                'verbose_name_plural': 'Reviews - Series',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.TextField(blank=True, max_length=200, null=True)),
                ('actors', models.TextField(blank=True, max_length=200, null=True)),
                ('sinopse', models.TextField(max_length=200)),
                ('rated', models.CharField(blank=True, choices=[('TV-Y', 'TV-Y'), ('TV-Y7', 'TV-Y7'), ('TV-Y7-FV', 'TV-Y7-FV'), ('TV-G', 'TV-G'), ('TV-PG', 'TV-PG'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA')], max_length=20, null=True)),
                ('poster_url', models.CharField(max_length=200)),
                ('launch_date', models.CharField(blank=True, max_length=20, null=True)),
                ('episodes', models.IntegerField()),
                ('seasons', models.IntegerField(blank=True, null=True)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('user_reviews', models.ManyToManyField(through='gestao.ReviewSeries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reviewseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestao.series'),
        ),
    ]
