# Generated by Django 5.1.7 on 2025-03-27 00:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewMovies',
            new_name='ReviewsMovies',
        ),
        migrations.RenameModel(
            old_name='ReviewSeries',
            new_name='ReviewsSeries',
        ),
    ]
