# Generated by Django 5.1.7 on 2025-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userprofiles',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='users',
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='gestao.userprofiles'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='plans',
            field=models.CharField(blank=True, choices=[('BASIC', 'BASIC'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=20, null=True),
        ),
    ]
