# Generated by Django 5.1.7 on 2025-03-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_rename_name_movies_title_rename_name_series_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='useraccounts',
            options={'verbose_name': 'UserAccount', 'verbose_name_plural': 'UserAccounts'},
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
    ]
