# Generated by Django 5.1.7 on 2025-03-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_movies_options_alter_series_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='sinopse',
            new_name='plot',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='sinopse',
            new_name='plot',
        ),
    ]
