# Generated by Django 5.1.7 on 2025-03-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_rename_sinopse_movies_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='runtime',
            field=models.CharField(blank=True, null=True),
        ),
    ]
