# Generated by Django 5.1.7 on 2025-03-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_movies_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='episodes',
        ),
    ]
