# Generated by Django 5.1.7 on 2025-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_series_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='favorites_series',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='favorites',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
