# Generated by Django 5.1.7 on 2025-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_remove_userprofiles_favorites_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='watchlist_series',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='watching',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
