# Generated by Django 5.1.7 on 2025-03-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_remove_userprofiles_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='likeability',
        ),
    ]
